// <auto-generated />
using System;
using M2Manager.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace M2Manager.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260805231311_Payers")]
    partial class Payers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("M2Manager.Api.Data.ExpenseCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ExpenseCategories");
                });

            modelBuilder.Entity("M2Manager.Api.Data.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Amount")
                        .HasColumnType("numeric(12,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasDefaultValue("PLN");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int?>("ExpenseCategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("ImageObjectKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateOnly?>("IssueDate")
                        .HasColumnType("date");

                    b.Property<string>("OcrLineItemsJson")
                        .HasColumnType("text");

                    b.Property<string>("OcrRawResponse")
                        .HasColumnType("text");

                    b.Property<int>("OcrStatus")
                        .HasColumnType("integer");

                    b.Property<int?>("PayerId")
                        .HasColumnType("integer");

                    b.Property<int>("PropertyId")
                        .HasColumnType("integer");

                    b.Property<int?>("RoomId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Vendor")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.HasIndex("ExpenseCategoryId");

                    b.HasIndex("PayerId");

                    b.HasIndex("RoomId");

                    b.HasIndex("PropertyId", "IssueDate");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("M2Manager.Api.Data.Payer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Payers");
                });

            modelBuilder.Entity("M2Manager.Api.Data.Property", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<decimal>("DefaultRoomHeightM")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(5,2)")
                        .HasDefaultValue(2.60m);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Purpose")
                        .HasColumnType("integer");

                    b.Property<decimal?>("TotalAreaM2")
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Properties");
                });

            modelBuilder.Entity("M2Manager.Api.Data.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("ExcludedWallAreaM2")
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal?>("FloorAreaM2")
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("GeometryJson")
                        .HasColumnType("text");

                    b.Property<decimal?>("HeightM")
                        .HasColumnType("numeric(5,2)");

                    b.Property<bool>("IncludeInTotals")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<decimal?>("LengthM")
                        .HasColumnType("numeric(8,3)");

                    b.Property<decimal?>("ManualCeilingAreaM2")
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal?>("ManualWallAreaM2")
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("PropertyId")
                        .HasColumnType("integer");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<decimal?>("WidthM")
                        .HasColumnType("numeric(8,3)");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId", "SortOrder");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("M2Manager.Api.Data.RoomOpening", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Count")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<decimal>("HeightCm")
                        .HasColumnType("numeric(8,1)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal?>("OffsetCm")
                        .HasColumnType("numeric(8,1)");

                    b.Property<int>("RoomId")
                        .HasColumnType("integer");

                    b.Property<bool>("SubtractFromWalls")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<int?>("WallSide")
                        .HasColumnType("integer");

                    b.Property<decimal>("WidthCm")
                        .HasColumnType("numeric(8,1)");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("RoomOpenings");
                });

            modelBuilder.Entity("M2Manager.Api.Data.Shop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Shops");
                });

            modelBuilder.Entity("M2Manager.Api.Data.ShoppingCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ShoppingCategories");
                });

            modelBuilder.Entity("M2Manager.Api.Data.ShoppingItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("ActualCost")
                        .HasColumnType("numeric(12,2)");

                    b.Property<string>("AssignedTo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CalculationNotes")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int?>("InvoiceId")
                        .HasColumnType("integer");

                    b.Property<string>("Link")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("OrdinalNo")
                        .HasColumnType("integer");

                    b.Property<int?>("PayerId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("PlannedBudget")
                        .HasColumnType("numeric(12,2)");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<int>("PropertyId")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("PurchaseDate")
                        .HasColumnType("date");

                    b.Property<decimal?>("Quantity")
                        .HasColumnType("numeric(12,3)");

                    b.Property<int?>("RoomId")
                        .HasColumnType("integer");

                    b.Property<int?>("ShoppingCategoryId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal?>("TotalCost")
                        .HasColumnType("numeric(12,2)");

                    b.Property<string>("Unit")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal?>("UnitCost")
                        .HasColumnType("numeric(12,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Vendor")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("PayerId");

                    b.HasIndex("RoomId");

                    b.HasIndex("ShoppingCategoryId");

                    b.HasIndex("Status");

                    b.HasIndex("PropertyId", "OrdinalNo");

                    b.ToTable("ShoppingItems");
                });

            modelBuilder.Entity("M2Manager.Api.Data.Invoice", b =>
                {
                    b.HasOne("M2Manager.Api.Data.ExpenseCategory", "ExpenseCategory")
                        .WithMany("Invoices")
                        .HasForeignKey("ExpenseCategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("M2Manager.Api.Data.Payer", "Payer")
                        .WithMany("Invoices")
                        .HasForeignKey("PayerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("M2Manager.Api.Data.Property", "Property")
                        .WithMany("Invoices")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("M2Manager.Api.Data.Room", "Room")
                        .WithMany("Invoices")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ExpenseCategory");

                    b.Navigation("Payer");

                    b.Navigation("Property");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("M2Manager.Api.Data.Room", b =>
                {
                    b.HasOne("M2Manager.Api.Data.Property", "Property")
                        .WithMany("Rooms")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");
                });

            modelBuilder.Entity("M2Manager.Api.Data.RoomOpening", b =>
                {
                    b.HasOne("M2Manager.Api.Data.Room", "Room")
                        .WithMany("Openings")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("M2Manager.Api.Data.ShoppingItem", b =>
                {
                    b.HasOne("M2Manager.Api.Data.Invoice", "Invoice")
                        .WithMany("ShoppingItems")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("M2Manager.Api.Data.Payer", "Payer")
                        .WithMany("ShoppingItems")
                        .HasForeignKey("PayerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("M2Manager.Api.Data.Property", "Property")
                        .WithMany("ShoppingItems")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("M2Manager.Api.Data.Room", "Room")
                        .WithMany("ShoppingItems")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("M2Manager.Api.Data.ShoppingCategory", "ShoppingCategory")
                        .WithMany("Items")
                        .HasForeignKey("ShoppingCategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Invoice");

                    b.Navigation("Payer");

                    b.Navigation("Property");

                    b.Navigation("Room");

                    b.Navigation("ShoppingCategory");
                });

            modelBuilder.Entity("M2Manager.Api.Data.ExpenseCategory", b =>
                {
                    b.Navigation("Invoices");
                });

            modelBuilder.Entity("M2Manager.Api.Data.Invoice", b =>
                {
                    b.Navigation("ShoppingItems");
                });

            modelBuilder.Entity("M2Manager.Api.Data.Payer", b =>
                {
                    b.Navigation("Invoices");

                    b.Navigation("ShoppingItems");
                });

            modelBuilder.Entity("M2Manager.Api.Data.Property", b =>
                {
                    b.Navigation("Invoices");

                    b.Navigation("Rooms");

                    b.Navigation("ShoppingItems");
                });

            modelBuilder.Entity("M2Manager.Api.Data.Room", b =>
                {
                    b.Navigation("Invoices");

                    b.Navigation("Openings");

                    b.Navigation("ShoppingItems");
                });

            modelBuilder.Entity("M2Manager.Api.Data.ShoppingCategory", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
